[DSD-5825] add maven publis and update publish artifact.gradle
mosip/secure-keystore pull request #81
Opened 2024-07-30 16:56 UTC by abhip2565

2024-07-30 17:45 UTC, sree96 commented on .github/workflows/android-artifact-build.yml
> +    uses: tw-mosip/kattu/.github/workflows/maven-publish.yml@master
Why tw-mosip?

2024-07-30 17:45 UTC, sree96 commented on android/publish-artifact.gradle
> +
Remove extra spaces

2024-07-30 17:47 UTC, sree96 requested changes
Address the comments please

2024-07-30 17:48 UTC, swatigoel approved these changes

2024-07-30 17:50 UTC, sree96 approved these changes

2024-07-31 06:45 UTC, swatigoel approved these changes

2024-07-31 06:55 UTC, merged